[build]
  command = "cd client && npm install && npm run build"
  publish = "client/.next"

[build.environment]
  NODE_ENV = "production"

[dev]
  command = "cd server && npm install && npm run start"
  publish = "client/build"
  functions = "server/functions"